### ISSUE TITLE
are models available?  yes, model repo unlinked in github but present in paper

### ISSUE THREAD

**Issue by colindaven** [weberlab-hhu/Predmoter#2]
Hello,

thanks for this. I've been trying Helixer recently with pretty interesting results so thought this might be worth a go too. 

Maybe I missed it on the github repo, but are pre-trained models available or going to be made available ?

Edit - I just found it via the paper here 
https://github.com/weberlab-hhu/predmoter_models

Thanks and best wishes,
Colin

**Comment by felicitas215** [comment]
The main Predmoter repository now links to the pretrained models.

**Comment by felicitas215** [comment]
The main Predmoter repository now links to the pretrained models.
